name = "onion's-utilities"
author = "btwonion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4e17fddb8d44dc43f40a043aa432d3681d0b36282709cfe83920054e47b1208"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
