name = "onion's-utilities"
author = "btwonion"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db44e07c2a27b132913bd5445864b72a80d920929d270328951afed706d1fa2a"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
