name = "onions-utilities"
author = "btwonion"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28016842ccdf178e1aa01a417e55419ac23cf034696b085de0bd2a8840d1aad0"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
