name = "onions-utilities"
author = "btwonion"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64c181a506330dcf964192634c38a8ab23586222d97a97ea13a8f49b53256f47"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
