name = "onion's-utilities"
author = "btwonion"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db21950546cc12ce0ff35ae3220306aa030da83ba69a783e91a1ed88514de23f"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
