name = "onions-utilities"
author = "btwonion"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "010a168b2c1ec3bf8eb831e7a6523ea35be6419c76154527ca28e7df5e3aa6f4"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
