name = "onion's-utilities"
author = "btwonion"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db59268d6c19e9220a0e13e25f9fee8b010c4592a8f43fcb86b77e862561121e"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
