name = "onion's-utilities"
author = "btwonion"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df1c6ce1acca6c7827121311630659d061fd389425c6229e13ae283973fe6c7c"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
