name = "onions-utilities"
author = "btwonion"
version = "2.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a92a0133edf86b2cc80bb9119e1fa2bada6e787e9a4ab459b0ac2d9f66adf239"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
