name = "onion's-utilities"
author = "btwonion"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aca25d630d56967f61dcdecb3ad3d9279b23bbb1ca15effbe6af28e607f9045"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
